### ISSUE TITLE
Using filters - Examples?

### ISSUE THREAD

**Issue by haraldkubota** [codeljo/AA_MCP2515#1]
Hi,

Trying to use filters...and they don't do what I expect them to do. Unfortunately there's no example for using them. Would it be possible to have a working example which filters out a range of IDs?

What I know is that this won't work, with eid=0 or 1:

```
CAN.begin(CANController::Mode::Normal);
CAN.setFiltersRxb0(0x100, 0x103, 0x07ff, 1);
CAN.setFiltersRxb1(0x100, 0x100, 0x100, 0x100, 0x07ff, 1);
CAN.setFilters(1);
```

I send IDs from 0x100 to 0x10F and I would only want to see 0x100 and 0x103. However I receive every message.
I guess I am doing something fundamentally wrong, but the source code does not help me either.
A working example (with and without eid) would be super-useful to have.

**Comment by codeljo** [comment]
Hi, The filters can only be modified when in Config mode.
I'll add an example showing filter usage asap but try the changes below. Below assumes 11-bit ID's.

**Update: See next comment for complete example.**

```cpp
CAN.begin(CANController::Mode::Config);
CAN.setFiltersRxb0(0x100, 0x103, 0x07ff, false);
CAN.setFiltersRxb1(0x100, 0x100, 0x100, 0x100, 0x07ff, false);
CAN.setFilters(true);
CAN.setMode(CANController::Mode::Normal);
```

**Comment by codeljo** [comment]
There is now an example for setting up the receive filters:
https://github.com/codeljo/AA_MCP2515/blob/3136ab4b1489a2e4bb08819c8c68dd4c45ed004d/examples/can_receive_filters/can_receive_filters.ino

Hope it helps and I'll be sure to continue improving the documentation. Thanks

**Comment by haraldkubota** [comment]
Thanks for the quick reply! It works! I have yet to find out what I did wrong. It's not the filter setup as that is the same. Anyway, works now.

Awesome! Nice library, especially since it works as expected!

**Comment by haraldkubota** [comment]
Example works as advertised!

**Comment by haraldkubota** [comment]
I found the issue which caused the filters to NOT work:

This part in setup() of various examples, specifically the receiving examples, does _not_ make the filters work:

```
  while(CAN.begin(CANController::Mode::Normal) != CANController::OK) {
    Serial.println("CAN begin FAIL - delaying for 1 second");
    delay(1000);
  }
  Serial.println("CAN begin OK");
```

while this from your recent filter example works:

```
  while(CAN.begin(CANController::Mode::Config) != CANController::OK) {
    Serial.println("CAN begin FAIL - delaying for 1 second");
    delay(1000);
  }
  Serial.println("CAN begin OK");
```

The difference is the `CAN.begin(CANController::Mode::Config)` and the subsequent ` CAN.setMode(CANController::Mode::Normal);
`

**Comment by codeljo** [comment]
I'm glad you got it working! Yes, That is the exact issue. I should have made it more clear that the filters can only be modified when in Config mode.

As you noted the other examples could be modified in a similiar way to the filter example or just do something like below after CAN.begin(CANController::Mode::Normal)

### Filter setup
```cpp
CAN.setMode(CANController::Mode::Config);
CAN.setFiltersRxb0(0x100, 0x103, 0x07ff, false);
CAN.setFiltersRxb1(0x100, 0x100, 0x100, 0x100, 0x07ff, false);
CAN.setFilters(true);
CAN.setMode(CANController::Mode::Normal);
```
